// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PostgreSQLCovidBrProcessFile.Model;

namespace PostgreSQLCovidBrProcessFile.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20210428223002_InitDadosCovid19BR")]
    partial class InitDadosCovid19BR
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("PostgreSQLCovidBrProcessFile.Model.DadosCovid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("city")
                        .HasColumnType("text");

                    b.Property<string>("city_ibge_code")
                        .HasColumnType("text");

                    b.Property<long>("city_ibglast_available_confirmede_code")
                        .HasColumnType("bigint");

                    b.Property<bool>("dadosAtualizados")
                        .HasColumnType("boolean");

                    b.Property<bool>("dadosNovos")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("epidemiological_week")
                        .HasColumnType("text");

                    b.Property<long>("estimated_population")
                        .HasColumnType("bigint");

                    b.Property<long>("estimated_population_2019")
                        .HasColumnType("bigint");

                    b.Property<string>("is_last")
                        .HasColumnType("text");

                    b.Property<string>("is_repeated")
                        .HasColumnType("text");

                    b.Property<double>("last_available_confirmed_per_100k_inhabitants")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("last_available_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("last_available_death_rate")
                        .HasColumnType("double precision");

                    b.Property<long>("last_available_deaths")
                        .HasColumnType("bigint");

                    b.Property<long>("new_confirmed")
                        .HasColumnType("bigint");

                    b.Property<long>("new_deaths")
                        .HasColumnType("bigint");

                    b.Property<long>("order_for_place")
                        .HasColumnType("bigint");

                    b.Property<string>("place_type")
                        .HasColumnType("text");

                    b.Property<string>("state")
                        .HasColumnType("text");

                    b.Property<string>("uId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OsDadosDoCovid");
                });
#pragma warning restore 612, 618
        }
    }
}
