// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MsSqlCovidBrFileProcess.Model;

namespace MsSqlCovidBrFileProcess.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20210605034420_InitDadosCovid19BR")]
    partial class InitDadosCovid19BR
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MsSqlCovidBrFileProcess.Model.DadosCovid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("city")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("city_ibge_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("city_ibglast_available_confirmede_code")
                        .HasColumnType("bigint");

                    b.Property<bool>("dadosAtualizados")
                        .HasColumnType("bit");

                    b.Property<bool>("dadosNovos")
                        .HasColumnType("bit");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<string>("epidemiological_week")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("estimated_population")
                        .HasColumnType("bigint");

                    b.Property<long>("estimated_population_2019")
                        .HasColumnType("bigint");

                    b.Property<string>("is_last")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("is_repeated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("last_available_confirmed_per_100k_inhabitants")
                        .HasColumnType("float");

                    b.Property<DateTime>("last_available_date")
                        .HasColumnType("datetime2");

                    b.Property<double>("last_available_death_rate")
                        .HasColumnType("float");

                    b.Property<long>("last_available_deaths")
                        .HasColumnType("bigint");

                    b.Property<long>("new_confirmed")
                        .HasColumnType("bigint");

                    b.Property<long>("new_deaths")
                        .HasColumnType("bigint");

                    b.Property<long>("order_for_place")
                        .HasColumnType("bigint");

                    b.Property<string>("place_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("state")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("uId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OsDadosDoCovid");
                });
#pragma warning restore 612, 618
        }
    }
}
